import jsPDF from 'jspdf'
import type { RoadmapLevel, SubTopic } from '@/types/roadmap'

export class PDFGenerator {
  private doc: jsPDF
  private pageHeight: number
  private pageWidth: number
  private margin: number
  private currentY: number
  private lineHeight: number

  constructor() {
    this.doc = new jsPDF()
    this.pageHeight = this.doc.internal.pageSize.height
    this.pageWidth = this.doc.internal.pageSize.width
    this.margin = 20
    this.currentY = this.margin
    this.lineHeight = 7
    
    // White background (default)
  }

  private addNewPageIfNeeded(requiredSpace: number = 20): void {
    if (this.currentY + requiredSpace > this.pageHeight - this.margin) {
      this.doc.addPage()
      this.currentY = this.margin
    }
  }

  private addText(text: string, fontSize: number = 10, style: 'normal' | 'bold' = 'normal', color: [number, number, number] = [30, 30, 30]): void {
    this.doc.setFontSize(fontSize)
    this.doc.setFont('helvetica', style)
    this.doc.setTextColor(color[0], color[1], color[2])
    
    const maxWidth = this.pageWidth - (this.margin * 2)
    const lines = this.doc.splitTextToSize(text, maxWidth)
    
    for (const line of lines) {
      this.addNewPageIfNeeded()
      this.doc.text(line, this.margin, this.currentY)
      this.currentY += this.lineHeight
    }
  }

  private addFormattedText(text: string, fontSize: number = 10, style: 'normal' | 'bold' = 'normal', color: [number, number, number] = [50, 50, 50], indent: number = 0): void {
    if (!text || !text.trim()) return
    
    this.doc.setFontSize(fontSize)
    this.doc.setFont('helvetica', style)
    this.doc.setTextColor(color[0], color[1], color[2])
    
    const maxWidth = this.pageWidth - (this.margin * 2) - indent
    const lines = this.doc.splitTextToSize(text.trim(), maxWidth)
    
    for (const line of lines) {
      this.addNewPageIfNeeded()
      this.doc.text(line, this.margin + indent, this.currentY)
      this.currentY += this.lineHeight
    }
  }

  private addTitle(text: string, fontSize: number = 16, color: [number, number, number] = [139, 92, 246]): void {
    this.addNewPageIfNeeded(15)
    this.currentY += 5
    this.addText(text, fontSize, 'bold', color)
    this.currentY += 5
  }

  private addSubtitle(text: string, fontSize: number = 12, color: [number, number, number] = [30, 30, 30]): void {
    this.addNewPageIfNeeded(12)
    this.currentY += 3
    this.addText(text, fontSize, 'bold', color)
    this.currentY += 2
  }

  private addSeparator(): void {
    this.addNewPageIfNeeded(10)
    this.currentY += 3
    this.doc.setDrawColor(200, 200, 200)
    this.doc.setLineWidth(0.5)
    this.doc.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY)
    this.currentY += 8
  }

  private addHeader(): void {
    // Violet gradient background
    this.doc.setFillColor(139, 92, 246) // violet-500
    this.doc.rect(this.margin, this.margin, this.pageWidth - (this.margin * 2), 30, 'F')
    
    // Add border
    this.doc.setDrawColor(124, 58, 237) // violet-600
    this.doc.setLineWidth(0.5)
    this.doc.rect(this.margin, this.margin, this.pageWidth - (this.margin * 2), 30, 'S')
    
    // White text on violet background
    this.doc.setTextColor(255, 255, 255)
    this.doc.setFontSize(22)
    this.doc.setFont('helvetica', 'bold')
    this.doc.text('DevOdos Learning Roadmap', this.margin + 10, this.margin + 20)
    
    this.currentY = this.margin + 40
  }

  private addFooter(pageNum: number, totalPages: number): void {
    const footerY = this.pageHeight - 15
    this.doc.setFontSize(8)
    this.doc.setTextColor(100, 100, 100)
    this.doc.text(`Generated by DevOdos | Page ${pageNum} of ${totalPages}`, this.margin, footerY)
    const dateText = `Generated on ${new Date().toLocaleDateString()}`
    const dateTextWidth = this.doc.getTextWidth(dateText)
    this.doc.text(dateText, this.pageWidth - this.margin - dateTextWidth, footerY)
  }

  private parseAndFormatExplanation(explanation: string): void {
    const cleanedExplanation = explanation
      .replace(/\*\*\*/g, '')
      .replace(/\*\*/g, '')
      .replace(/#{3,}/g, '##')

    const lines = cleanedExplanation.split('\n')
    let skipNextEmpty = false

    for (let i = 0; i < lines.length; i++) {
      const trimmedLine = lines[i].trim()

      if (!trimmedLine && skipNextEmpty) {
        skipNextEmpty = false
        continue
      }

      if (trimmedLine.match(/^##\s*(📚|📖)?\s*(overview|what is|introduction|definition)/i)) {
        this.addSubtitle('[OVERVIEW & DEFINITION]', 12, [139, 92, 246]) // violet-500
        skipNextEmpty = true
        continue
      } else if (trimmedLine.match(/^##\s*(🎯)?\s*(core concepts?|key principles?|fundamentals?)/i)) {
        this.addSubtitle('[CORE CONCEPTS & PRINCIPLES]', 12, [59, 130, 246]) // blue-500
        skipNextEmpty = true
        continue
      } else if (trimmedLine.match(/^##\s*(🔧|⚙️)?\s*(technical implementation|implementation|how to)/i)) {
        this.addSubtitle('[TECHNICAL IMPLEMENTATION]', 12, [16, 185, 129]) // emerald-500
        skipNextEmpty = true
        continue
      } else if (trimmedLine.match(/^##\s*(💡)?\s*(practical .*use cases?|examples?|use cases?)/i)) {
        this.addSubtitle('[PRACTICAL USE CASES]', 12, [245, 158, 11]) // amber-500
        skipNextEmpty = true
        continue
      } else if (trimmedLine.match(/^##\s*(✅)?\s*(best practices?|recommendations?|standards?)/i)) {
        this.addSubtitle('[BEST PRACTICES & STANDARDS]', 12, [6, 182, 212]) // cyan-500
        skipNextEmpty = true
        continue
      } else if (trimmedLine.match(/^##\s*(⚠️|❌)?\s*(common pitfalls?|mistakes?|what to avoid)/i)) {
        this.addSubtitle('[COMMON PITFALLS & SOLUTIONS]', 12, [244, 63, 94]) // rose-500
        skipNextEmpty = true
        continue
      } else if (trimmedLine.match(/^##\s*(🚀)?\s*(advanced topics?)/i)) {
        this.addSubtitle('[ADVANCED TOPICS]', 12, [168, 85, 247]) // purple-500
        skipNextEmpty = true
        continue
      } else if (trimmedLine.match(/^##\s*(💼)?\s*(career|professional|industry impact)/i)) {
        this.addSubtitle('[CAREER & INDUSTRY IMPACT]', 12, [99, 102, 241]) // indigo-500
        skipNextEmpty = true
        continue
      } else if (trimmedLine.match(/^##\s*(📖)?\s*(next steps?|learning path|what.*next|further)/i)) {
        this.addSubtitle('[LEARNING PATH & NEXT STEPS]', 12, [20, 184, 166]) // teal-500
        skipNextEmpty = true
        continue
      } else if (trimmedLine.startsWith('##')) {
        const headerText = trimmedLine.replace(/^##\s*(?:[📚📖🎯🔧⚙️💡✅⚠️❌🚀💼📖])?\s*/, '').toUpperCase()
        this.addSubtitle(`[${headerText}]`, 12, [139, 92, 246]) // violet-500
        skipNextEmpty = true
        continue
      }

      if (!trimmedLine) {
        this.currentY += 1
        continue
      }

      if (trimmedLine.match(/^[-•*]\s+/)) {
        const bulletContent = trimmedLine.replace(/^[-•*]\s+/, '').trim()
        if (bulletContent) {
          this.addFormattedText(`• ${bulletContent}`, 10, 'normal', [50, 50, 50], 10)
        }
      } else if (trimmedLine.match(/^\d+\./)) {
        const numberedContent = trimmedLine.replace(/^\d+\.\s*/, '').trim()
        const number = trimmedLine.match(/^(\d+)\./)?.[1] || '1'
        if (numberedContent) {
          this.addFormattedText(`${number}. ${numberedContent}`, 10, 'normal', [50, 50, 50], 10)
        }
      } else if (trimmedLine.startsWith('```')) {
        continue
      } else {
        this.addFormattedText(trimmedLine, 10, 'normal', [50, 50, 50])
        this.currentY += 1
      }
    }
  }

  public generateSubtopicPDF(subtopic: SubTopic, explanation: string, technology?: string): void {
    this.addHeader()
    
    this.addTitle(subtopic.title, 18, [139, 92, 246]) // violet-500
    
    this.addSubtitle('Description:', 12, [30, 30, 30])
    this.addText(subtopic.desc, 10, 'normal', [50, 50, 50])
    
    if (technology) {
      this.addSubtitle(`Technology Context: ${technology}`, 12, [139, 92, 246]) // violet-500
    }
    
    this.addSeparator()
    
    this.addSubtitle('Comprehensive Learning Guide:', 14, [139, 92, 246]) // violet-500
    this.parseAndFormatExplanation(explanation)
    
    this.addSeparator()
    
    this.addSubtitle('[STUDY TIPS & RECOMMENDATIONS]', 12, [16, 185, 129]) // emerald-500
    this.addFormattedText('• Break down complex concepts into smaller, manageable parts', 10, 'normal', [50, 50, 50], 10)
    this.addFormattedText('• Practice with real-world examples and hands-on projects', 10, 'normal', [50, 50, 50], 10)
    this.addFormattedText('• Join developer communities and forums for additional support', 10, 'normal', [50, 50, 50], 10)
    this.addFormattedText('• Document your learning journey and track your progress', 10, 'normal', [50, 50, 50], 10)
    
    const totalPages = this.doc.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      this.doc.setPage(i)
      this.addFooter(i, totalPages)
    }
  }

  public generateFullRoadmapPDF(roadmapData: RoadmapLevel[], goal: string, level: string, language: string): void {
    this.addHeader()
    
    this.addTitle(`${goal} Learning Roadmap`, 20, [139, 92, 246]) // violet-500
    
    this.addSubtitle('Roadmap Details:', 12, [30, 30, 30])
    this.addText(`Goal: ${goal}`, 10, 'bold', [50, 50, 50])
    this.addText(`Experience Level: ${level}`, 10, 'bold', [50, 50, 50])
    this.addText(`Primary Language: ${language}`, 10, 'bold', [50, 50, 50])
    this.addText(`Generated: ${new Date().toLocaleDateString()}`, 10, 'normal', [100, 100, 100])
    
    this.addSeparator()
    
    this.addTitle('[TABLE OF CONTENTS]', 16, [139, 92, 246]) // violet-500
    roadmapData.forEach((levelData, levelIndex) => {
      this.addText(`${levelIndex + 1}. ${levelData.level}`, 11, 'bold', [59, 130, 246]) // blue-500
      levelData.nodes.forEach((node, nodeIndex) => {
        this.addFormattedText(`${levelIndex + 1}.${nodeIndex + 1} ${node.title}`, 10, 'normal', [50, 50, 50], 15)
      })
    })
    
    this.addSeparator()
    
    roadmapData.forEach((levelData, levelIndex) => {
      this.addNewPageIfNeeded(30)
      
      this.addTitle(`${levelIndex + 1}. ${levelData.level}`, 18, [139, 92, 246]) // violet-500
      
      levelData.nodes.forEach((node, nodeIndex) => {
        this.addNewPageIfNeeded(25)
        
        this.addSubtitle(`${levelIndex + 1}.${nodeIndex + 1} ${node.title}`, 14, [16, 185, 129]) // emerald-500
        this.addText(node.description, 10, 'normal', [50, 50, 50])
        this.currentY += 3
        
        this.addText('Learning Topics:', 11, 'bold', [30, 30, 30])
        node.subTopics.forEach((subtopic, subtopicIndex) => {
          this.addNewPageIfNeeded(15)
          this.addFormattedText(`${subtopicIndex + 1}. ${subtopic.title}`, 10, 'bold', [59, 130, 246], 10) // blue-500
          this.addFormattedText(`${subtopic.desc}`, 9, 'normal', [100, 100, 100], 20) // slate-400
          this.currentY += 2
        })
        
        if (nodeIndex < levelData.nodes.length - 1) {
          this.currentY += 5
        }
      })
      
      if (levelIndex < roadmapData.length - 1) {
        this.addSeparator()
      }
    })
    
    const totalPages = this.doc.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      this.doc.setPage(i)
      this.addFooter(i, totalPages)
    }
  }

  public save(filename: string): void {
    this.doc.save(filename)
  }
}

export const downloadSubtopicPDF = async (
  subtopic: SubTopic,
  explanation: string,
  technology?: string
): Promise<void> => {
  const generator = new PDFGenerator()
  generator.generateSubtopicPDF(subtopic, explanation, technology)
  
  const filename = `${subtopic.title.replace(/[^a-zA-Z0-9]/g, '_')}_guide.pdf`
  generator.save(filename)
}

export const downloadFullRoadmapPDF = (
  roadmapData: RoadmapLevel[],
  goal: string,
  level: string,
  language: string
): void => {
  const generator = new PDFGenerator()
  generator.generateFullRoadmapPDF(roadmapData, goal, level, language)
  
  const filename = `${goal.replace(/[^a-zA-Z0-9]/g, '_')}_roadmap.pdf`
  generator.save(filename)
}
